CREATE TABLE concert (
       id long GENERATED BY DEFAULT AS IDENTITY,
       name varchar(255),
        PRIMARY KEY (id)
);

CREATE TABLE payment (
    id long,
    user_id long,
    reservation_id long,
    price int
);